<?php
/**
 * Created by PhpStorm.
 * User: jiechengkeji
 * Date: 2017/8/9
 * Time: 14:12
 */

namespace Home\Controller;

use Home\Service\GpService;

class GpController extends AuthController
{
    private $gpService;

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->gpService = new GpService();
    }

    /**
     * 显示省列表
     */
    public function getProvince()
    {
        $result = $this->gpService->getProvince();
        $this->ajaxReturn($result);
    }

    /**
     * 显示城市列表
     */
    public function getCity()
    {
        $pid = I("pid");// 通过省的id获取市的列表
        $result = $this->gpService->getCity($pid);
        $this->ajaxReturn($result);
    }

    /**
     * 显示区的列表
     */
    public function getRegions()
    {
        $cid = I("cid",1);//通过市的列表获取区的列表// 默认取威海市数据
        $result = $this->gpService->getRegions($cid);
        $this->ajaxReturn($result);
    }

    /**
     * 通过区获取小区的列表
     */
    public function getVillage()
    {
        $rid = I("rid");//通过市的列表获取区的列表
        $result = $this->gpService->getVillage($rid);
        $this->ajaxReturn($result);
    }
}